### ISSUE TITLE
Add a flag to exit with a non-zero status code on warnings

### ISSUE THREAD

**Issue by SamirTalwar** [rust-lang/rust-clippy#12300]
### Description

We can now configure the various levels of each lint option in _Cargo.toml_. I currently have one that looks like this:

```toml
[workspace.lints.clippy]
all = { level = "warn", priority = 0 }
pedantic = { level = "warn", priority = 0 }
# disable some pedantic warnings which feel a little too pedantic
doc_markdown = { level = "allow", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
must_use_candidate = { level = "allow", priority = 1 }
similar_names = { level = "allow", priority = 1 }
wildcard_imports = { level = "allow", priority = 1 }
# these should probably be enabled
default_trait_access = { level = "allow", priority = 2 }
from_iter_instead_of_collect = { level = "allow", priority = 2 }
large_futures = { level = "allow", priority = 2 }
needless_pass_by_value = { level = "allow", priority = 2 }
unnecessary_wraps = { level = "allow", priority = 2 }
unused_async = { level = "allow", priority = 2 }
```

I want to run Clippy in pre-commit checks and CI too, and in these situations, I want it to fail (exit with a non-zero status code) if any warnings are encountered.

Currently I have two ways of doing this:

1. using something like `sed` to rewrite _Cargo.toml_, replacing `"warn"` with `"deny"`, or
2. using flags to override the lints.

Neither of these seem great. Using `sed` is error-prone, especially when running it locally in a pre-commit hook, and if I use flags, I have to re-specify all of the "allow" lints, which means I probably have to generate the command-line arguments programmatically.

I would like a command-line argument that tells Clippy to fail on warnings instead. I suggest `--exit-with-failure-on-warnings`, though you may prefer something more terse.

I am happy to attempt to work on this feature myself, but I would like to discuss it to ensure that the maintainers of Clippy agree in principle first.

If I am missing an obvious way to achieve this, please let me know!

### Version

```text
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6
```
