### ISSUE TITLE
centralized lint configurations

### ISSUE THREAD

**Issue by andrewbanchich** [rust-lang/rust-clippy#13083]
### Description

It would be really great to be able to centralize Clippy lint configurations across packages. The current limitations of Clippy mean that, if a team maintains 20 packages in different repos, they will need to manage each package separately.

I'd think we could have a feature where we could add something like:

```toml
[lints.src]
git = "https://github.com/team-repo/clippy-config.git"
```

to `Cargo.toml`.

Is this something we'd be interested in adding?
