### ISSUE TITLE
Cargo.toml dependencies: avoid caret requirements

### ISSUE THREAD

**Issue by Marcondiro** [rust-lang/rust-clippy#13307]
### What it does

Hello,
It would be nice to have a lint that highlights the presence of dependencies having the version specified with a `^` (caret) in the `Cargo.toml`. For example `foo="^1.2.3"`.
As for [Cargo docs](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements):
> Leaving off the caret is a simplified equivalent syntax to using caret requirements. While caret requirements are the default, it is recommended to use the simplified syntax when possible.

### Advantage

This lint helps in having a uniform `Cargo.toml` where simplified syntax and explicit carets are not mixed, following Cargo docs suggestion.

### Drawbacks

None I am aware of

### Example

```toml
[dependencies]
foo="^1.2.3"
bar="9.8.7"
```

Could be written as:

```toml
[dependencies]
foo="1.2.3"
bar="9.8.7"
```
