### ISSUE TITLE
allow-unwrap-in-tests (etc) do not work for integration tests / examples / benches

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust-clippy#13981]
Clippy lets you do the following:

```toml
# Cargo.toml
[lints.clippy]
unwrap-used = true

# clippy.toml
allow-unwrap-in-tests = true
```

This stops code that is `cfg(test)` or `#[test]` from getting linted. However, this does not affect code in `test/` (etc)., since that code isn't `cfg(test)`.

`is_in_test()` probably should take that into account?
