### ISSUE TITLE
`cargo test` can not apply `[lints]` configuration correctly

### ISSUE THREAD

**Issue by callanchen** [rust-lang/rust-clippy#14769]
### Summary

I wrote a lint to check the dependencies usage in `Cargo.toml` file.

So my ui-test cargo project need to use the external crates, I need to add them to `clippy/Cargo.toml`.

Importantly, I don't want this lint to check the `clippy` library itself. I changed its level to `allow` under `[lint]` in `clippy/Cargo.toml`, but when I run `cargo test`, the configuration does not take effect and it reports information about the `clippy` library itself.

However, when I use `cargo dev lint ./` , the `[lint]` configuration works.

I don't know why.

### Reproducer

I tried this code:

In my ui test project:
```toml
# Cargo.toml
des = "0.8.1" # Do not use it!
```

In clippy's `Cargo.toml` file:
```toml
# UI test dependencies
des = "0.8.1"

[lints]
clippy.pedantic = { level = "warn", priority = -1 }
clippy.weak_encryption_algorithm = "allow" # Here
```

I expected to see this happen:

Do not lint at `clippy` crate itself.

Instead, this happened:

It lints at `clippy` crate itself.

### Version

```text
rustc 1.88.0-nightly (78f2104e3 2025-04-16)
binary: rustc
commit-hash: 78f2104e334068d5a892a170d50193c0025c690e
commit-date: 2025-04-16
host: x86_64-unknown-linux-gnu
release: 1.88.0-nightly
LLVM version: 20.1.2
```
