### ISSUE TITLE
Clippy doesn't take into account configuration overrides given through `cargo --config` CLI

### ISSUE THREAD

**Issue by anlavandier** [rust-lang/rust-clippy#14786]
### Summary

Clippy will not take into account `cargo --config` CLI arguments. This leads to cases where `cargo clippy` is unable to resolve dependencies when `cargo build` and `cargo check` both can.   

### Reproducer

I built a new empty cargo project and added a single dependency (in my case `itertools` but it doesn't matter) and asked for a feature that doesn't exist in the version on crates.io. This leads to the following `Cargo.toml` : 
```toml
[package]
name = "clippy-bug-test"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = { version = "0.14", default-features = false, features = ["SomeNewFeature"] }
```
Naturally this doesn't compile.

Now to simulate having made a fork of `itertools` that includes the aforementioned feature (`SomeNewFeature`), I simply created another empty project in the directory `my-itertools`, named it `itertools` and added this single feature. Here's the `Cargo.toml`:

```toml                         
[package]
name = "itertools"
version = "0.14.0"
edition = "2024"

[features]
SomeNewFeature = []
```
The crate `clippy-bug-test` can now be build by using the following command:
```bash
~/clippy-bug-test$ cargo --config "patch.crates-io.itertools.path='/path/to/my-itertools'" build
```

I expected to see this happen:
```bash
~/clippy-bug-test$ cargo --config "patch.crates-io.itertools.path='/path/to/my-itertools'" clippy
```
to work normally, like `cargo build` and `cargo check` did.

Instead, this happened:
```bash
~/clippy-bug-test$ cargo --config "patch.crates-io.itertools.path='/path/to/my-itertools'" clippy
    Updating crates.io index
error: failed to select a version for `itertools`.
    ... required by package `clippy-bug-test v0.1.0 (/home/tribe/clippy-bug-test)`
versions that meet the requirements `^0.14` are: 0.14.0

the package `clippy-bug-test` depends on `itertools`, with features: `SomeNewFeature` but `itertools` does not have these features.


failed to select a version for `itertools` which could resolve this conflict
```

### Version

```text
rustc 1.86.0 (05f9846f8 2025-03-31)
binary: rustc
commit-hash: 05f9846f893b09a1be1fc8560e33fc3c815cfecb
commit-date: 2025-03-31
host: x86_64-unknown-linux-gnu
release: 1.86.0
LLVM version: 19.1.7
```
