### ISSUE TITLE
Restriction Lint: Crate License

### ISSUE THREAD

**Issue by mehcode** [rust-lang/rust-clippy#3867]
After seeing the new-ish cargo metadata lints, I was thinking it would interesting to have a lint like:

> **crate_license**
> Check the license information in the crate metadata and restrict to _something_. 

I imagine a whitelist/blacklist of licenses would be what most want. 

```toml
# in clippy.toml
blacklisted-licenses = ["MIT"]
whitelisted-licenses = ["MPL"]
```

This seems fairly straightforward to implement after reading some of the source for the cargo lints. If we want to do this I'd love to try to implement.
