### ISSUE TITLE
New lint: Optional dependency isn't actually optional

### ISSUE THREAD

**Issue by not-my-profile** [rust-lang/rust-clippy#8036]
### What it does

For the following `Cargo.toml` config:

```toml
[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"], optional = true }
```

Clippy would tell you: Are you sure that you want to mark the `tokio` dependency as optional? It isn't actually optional because your `reqwest` dependency depends on it.

### Categories (optional)

- Kind: cargo

Marking a dependency that isn't actually optional as optional is confusing.

### Drawbacks

None.
