### ISSUE TITLE
Adapt `doc-valid-idents` config to support list expansion instead of replacement

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust-clippy#8877]
### Description

The config value `doc-valid-idents` for [`doc_markdown`](https://rust-lang.github.io/rust-clippy/master/index.html#doc_markdown) is a list of allowed identifiers. I've seen some projects overriding them and only adding a few new values. It would be nice if the user also had the option to append new values to the list instead of replacing them.

I was thinking of something like a dummy value `..` that indicates that the default list should only be expanded. For example:

```toml
doc-valid-idents = ["OverRide"] # => Only `OverRide` is allwed 
doc-valid-idents = ["..", "Append"] # => Clippy's default plus override is allowed
```

This is just one suggestion, feel free to suggest other options :)

### Version

```text
Any *
```
